import styles from '../../components/subpage.module.css';

export const metadata = {
    title: 'Disclaimer',
    description: 'Disclaimer for Sanatan Sangam app and website.',
};

export default function Disclaimer() {
    return (
        <>
            <section className={styles.hero} style={{ padding: '48px 0 32px' }}>
                <div className={`container ${styles.heroContent}`}>
                    <h1 style={{ fontSize: 'clamp(1.8rem,4vw,2.5rem)' }}>Disclaimer</h1>
                    <p className={styles.heroDesc}>Last updated: February 2026</p>
                </div>
            </section>
            <section className="section" style={{ background: 'var(--cream)' }}>
                <div className="container" style={{ maxWidth: '800px' }}>
                    <div style={{ display: 'flex', flexDirection: 'column', gap: '24px', lineHeight: '1.8', fontSize: '0.95rem', color: 'var(--brown-mid)' }}>
                        <div>
                            <h3>Live Darshan</h3>
                            <p>Live temple streams are provided by official temple YouTube channels. Sanatan Sangam is not affiliated with these temples and does not own or control this content. We simply aggregate publicly available streams for devotee convenience.</p>
                        </div>
                        <div>
                            <h3>AI-Generated Content</h3>
                            <p>Content generated by our AI features (Artmate, Tunemate, Wishmate, Sanatan Chatbot) is produced by artificial intelligence and may not always be accurate. All AI-generated content is for personal, non-commercial use only.</p>
                        </div>
                        <div>
                            <h3>Astrology Services</h3>
                            <p>Horoscope predictions, Panchang data, and Kundli reports are for informational and entertainment purposes only. They should not be used as a substitute for professional advice.</p>
                        </div>
                        <div>
                            <h3>Third-Party Content</h3>
                            <p>Some features may display content from third-party sources. All trademarks, logos, and content belong to their respective owners.</p>
                        </div>
                        <div>
                            <h3>Removal Requests</h3>
                            <p>If you represent a temple or content owner and wish to have your stream or content removed, please contact us at <a href="mailto:hi@askyourguide.ai" style={{ color: 'var(--saffron)' }}>hi@askyourguide.ai</a></p>
                        </div>
                    </div>
                </div>
            </section>
        </>
    );
}
